### ISSUE TITLE
Feature request: children

### ISSUE THREAD

**Issue by lukebars** [callstack/reanimated-arc#5]
## Describe the feature

It would be nice if we could pass children to the arc. I could even submit a PR for that if anyone would agree with that kind of logic

## Motivation

Currently AFAIK we have to rely on absolute position to render anything inside the arc.

**Comment by jayu** [comment]
In the I initial version I had a possibility to put children at the end of the arc. So once arc was animated, position of the child followed the end of the arc. Is this your use case?
